/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulatorsederhana;

/**
 *
 * @author Acer
 */
public class nisakalkulator extends javax.swing.JFrame {

    String angka;
    double jumlah, bil1, bil2;
    int pilih;
    
    public nisakalkulator() {
        initComponents();
        angka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        tampil = new javax.swing.JTextField();
        tblhapus = new javax.swing.JButton();
        tblbagi = new javax.swing.JButton();
        tbl9 = new javax.swing.JButton();
        tblpersen = new javax.swing.JButton();
        tbl4 = new javax.swing.JButton();
        tblkali = new javax.swing.JButton();
        tbl8 = new javax.swing.JButton();
        tbl1 = new javax.swing.JButton();
        tbl6 = new javax.swing.JButton();
        tblkurang = new javax.swing.JButton();
        tbl7 = new javax.swing.JButton();
        tbl5 = new javax.swing.JButton();
        tbl3 = new javax.swing.JButton();
        tbltambah = new javax.swing.JButton();
        tbl2 = new javax.swing.JButton();
        tblkoma = new javax.swing.JButton();
        tblhasil = new javax.swing.JButton();
        tbn0 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblhapus.setText("c");
        tblhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblhapusActionPerformed(evt);
            }
        });

        tblbagi.setText("/");
        tblbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblbagiActionPerformed(evt);
            }
        });

        tbl9.setText("9");
        tbl9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl9ActionPerformed(evt);
            }
        });

        tblpersen.setText("%");
        tblpersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblpersenActionPerformed(evt);
            }
        });

        tbl4.setText("4");
        tbl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl4ActionPerformed(evt);
            }
        });

        tblkali.setText("X");
        tblkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblkaliActionPerformed(evt);
            }
        });

        tbl8.setText("8");
        tbl8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl8ActionPerformed(evt);
            }
        });

        tbl1.setText("1");
        tbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl1ActionPerformed(evt);
            }
        });

        tbl6.setText("6");
        tbl6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl6ActionPerformed(evt);
            }
        });

        tblkurang.setText("-");
        tblkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblkurangActionPerformed(evt);
            }
        });

        tbl7.setText("7");
        tbl7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl7ActionPerformed(evt);
            }
        });

        tbl5.setText("5");
        tbl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl5ActionPerformed(evt);
            }
        });

        tbl3.setText("3");
        tbl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl3ActionPerformed(evt);
            }
        });

        tbltambah.setText("+");
        tbltambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbltambahActionPerformed(evt);
            }
        });

        tbl2.setText("2");
        tbl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl2ActionPerformed(evt);
            }
        });

        tblkoma.setText(",");
        tblkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblkomaActionPerformed(evt);
            }
        });

        tblhasil.setText("=");
        tblhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblhasilActionPerformed(evt);
            }
        });

        tbn0.setText("0");
        tbn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tbn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblkoma, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tbltambah, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tblhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tampil, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tblhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tbl6, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(tbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tblpersen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tblkali, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tblkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tblbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tampil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblpersen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tblkali, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbltambah, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblkoma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbn0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn0ActionPerformed
       angka +="0";
       tampil.setText(angka);
    }//GEN-LAST:event_tbn0ActionPerformed

    private void tblhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblhasilActionPerformed
      switch(pilih){
          case 1:
              bil2 = Double.parseDouble(angka);
              jumlah = bil1+bil2;
              angka = Double.toString (jumlah);
              tampil.setText (angka);
              break;
           case 2:
              bil2 = Double.parseDouble(angka);
              jumlah = bil1-bil2;
              angka = Double.toString (jumlah);
              tampil.setText (angka);
              break;
           case 3:
              bil2 = Double.parseDouble(angka);
              jumlah = bil1*bil2;
              angka = Double.toString (jumlah);
              tampil.setText (angka);
              break;
           case 4:
              bil2 = Double.parseDouble(angka);
              jumlah = bil1/bil2;
              angka = Double.toString (jumlah);
              tampil.setText (angka);
              break;
           case 5:
              bil2 = Double.parseDouble(angka);
              jumlah = bil1%bil2;
              angka = Double.toString (jumlah);
              tampil.setText (angka);
              break;
      }     
    }//GEN-LAST:event_tblhasilActionPerformed

    private void tblhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblhapusActionPerformed
     tampil.setText (null);
     bil1=0.0;
     bil2=0.0;
     jumlah=0.0;
     angka="";
    }//GEN-LAST:event_tblhapusActionPerformed

    private void tbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl1ActionPerformed
       angka +="1";
       tampil.setText(angka);
    }//GEN-LAST:event_tbl1ActionPerformed

    private void tbl7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl7ActionPerformed
      angka +="7";
       tampil.setText(angka);
    }//GEN-LAST:event_tbl7ActionPerformed

    private void tbl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl2ActionPerformed
       angka +="2";
       tampil.setText(angka);
    }//GEN-LAST:event_tbl2ActionPerformed

    private void tbl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl3ActionPerformed
       angka +="3";
       tampil.setText(angka);
    }//GEN-LAST:event_tbl3ActionPerformed

    private void tbl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl4ActionPerformed
       angka +="4";
       tampil.setText(angka);
    }//GEN-LAST:event_tbl4ActionPerformed

    private void tbl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl5ActionPerformed
        angka +="5";
       tampil.setText(angka);
    }//GEN-LAST:event_tbl5ActionPerformed

    private void tbl6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl6ActionPerformed
       angka +="6";
       tampil.setText(angka);
    }//GEN-LAST:event_tbl6ActionPerformed

    private void tbl8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl8ActionPerformed
        angka +="8";
       tampil.setText(angka);
    }//GEN-LAST:event_tbl8ActionPerformed

    private void tbl9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl9ActionPerformed
       angka +="9";
       tampil.setText(angka);
    }//GEN-LAST:event_tbl9ActionPerformed

    private void tbltambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbltambahActionPerformed
       bil1 =Double.parseDouble(angka);
       tampil.setText("+");
       angka="";
       pilih=1;
    }//GEN-LAST:event_tbltambahActionPerformed

    private void tblkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblkurangActionPerformed
        bil1 =Double.parseDouble(angka);
       tampil.setText("-");
       angka="";
       pilih=2;
    }//GEN-LAST:event_tblkurangActionPerformed

    private void tblkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblkaliActionPerformed
      bil1 =Double.parseDouble(angka);
       tampil.setText("*");
       angka="";
       pilih=3;
    }//GEN-LAST:event_tblkaliActionPerformed

    private void tblbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblbagiActionPerformed
       bil1 =Double.parseDouble(angka);
       tampil.setText("/");
       angka="";
       pilih=4;
    }//GEN-LAST:event_tblbagiActionPerformed

    private void tblpersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblpersenActionPerformed
       bil1 =Double.parseDouble(angka);
       tampil.setText("%");
       angka="";
       pilih=5;
    }//GEN-LAST:event_tblpersenActionPerformed

    private void tblkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblkomaActionPerformed
         angka +=".";
       tampil.setText(angka);      
    }//GEN-LAST:event_tblkomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nisakalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nisakalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nisakalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nisakalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nisakalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField tampil;
    private javax.swing.JButton tbl1;
    private javax.swing.JButton tbl2;
    private javax.swing.JButton tbl3;
    private javax.swing.JButton tbl4;
    private javax.swing.JButton tbl5;
    private javax.swing.JButton tbl6;
    private javax.swing.JButton tbl7;
    private javax.swing.JButton tbl8;
    private javax.swing.JButton tbl9;
    private javax.swing.JButton tblbagi;
    private javax.swing.JButton tblhapus;
    private javax.swing.JButton tblhasil;
    private javax.swing.JButton tblkali;
    private javax.swing.JButton tblkoma;
    private javax.swing.JButton tblkurang;
    private javax.swing.JButton tblpersen;
    private javax.swing.JButton tbltambah;
    private javax.swing.JButton tbn0;
    // End of variables declaration//GEN-END:variables
}
